# NAS Configuration - Generated by setup.sh
# Regenerate with: ./scripts/setup.sh nas2
{
  # Identification
  nasName = "nas2";
  hostname = "nixos-nas2";

  # Network
  nasIP = "192.168.0.22";
  gateway = "192.168.0.1";
  nameservers = [ "192.168.0.11" "1.1.1.1" ];

  # Domain (for server integration)
  domain = "josecriane.com";
  subdomain = "in";

  # Administrator user
  adminUser = "sito";
  adminSSHKeys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCtNJ7Ps/rxgBQN/FpM6yCXhKVx7tisR3+ihUQFfAWVzSCvDz6Zt+L2uKCymijoi4aumnKK8kXdJSWPrtKIi4z58ljjg1FfOA0V6XYbtCKX+6B4Mrqvisi0QL2dwr7r4tyxEaye2DHozhGvQnUMKwvKLfXaEry2RzVNeBOkP2nJPh6i8dxtgZ4yOo8YutVqpl9J+FpNbUeP9DEv3rajCsFNVYAJ2SoouV2/ndcAVE/fincP3LhOmMaPSPK4JHV49ygKj1iMYsBbc9liNNRAB5hg+syFu8IQbQK9Oq8xwveY0kAzd61E5yrQiuTWFYevYWPrnycjkTEcDkFA359nKnd3jujvsqh8++3q2i/91RO/xFwRCd3P4ximJRMLeubgimZtp7Axcz4SxGpZXrm/YwHQz+IkbAhtCo4kxfUt7gnK2vu0tfCS3Sht+PYfT+n6BaETsI4gx3KulsTM/JMkDV08VullYQq8SO5XoIK+xxbtFG5KEGHHlwNH/AsdJ2dP4dKOo8I3xnuzYcadtQtYMabqGDk02eo8rqopApFlbav0OhWPwzMbk70IxAZbOcwx90SBUgqLGpnoGw7+ob9Zh4l+hqQplXQ8lcxhGjD3lsVmdaMtcFuAuBHY3DNkytWnMm1sBERxgKNhcy4+E/IQLNXRjqhvoHhXYVZeBXmMf50lSQ== jose.cribeiro@nomasystems.com"
  ];

  # User/group IDs
  puid = 1000;
  pgid = 1000;

  # Timezone
  timezone = "UTC";

  # Data disks (used by storage-mergerfs.nix and monitoring.nix)
  dataDisks = [ "disk1" "disk2" "disk3" ];

  # Services
  services = {
    samba = true;
    nfs = true;
    cockpit = true;
    filebrowser = true;
    authentikIntegration = true;
  };

  # LDAP (for Samba with Authentik)
  ldap = {
    enable = true;
    server = "192.168.0.5";
    baseDN = "dc=nas,dc=local";
  };
}
