let
  # Machine public keys (age format, generated by setup.sh)
  nas1 = "age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

  # Your public key for encrypting/decrypting
  admin = "age1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy";
in
{
  # Per-machine secrets
  "nas1/samba-password.age".publicKeys = [ nas1 admin ];
}
