let
  # NAS public key (age format, generated by setup.sh)
  nas = "age1y64gunf6z6g30zmyjan7xlc908g7576hlc3fsrdye2actztgt52s4x7hm6";

  # Your public key for encrypting/decrypting
  admin = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCtNJ7Ps/rxgBQN/FpM6yCXhKVx7tisR3+ihUQFfAWVzSCvDz6Zt+L2uKCymijoi4aumnKK8kXdJSWPrtKIi4z58ljjg1FfOA0V6XYbtCKX+6B4Mrqvisi0QL2dwr7r4tyxEaye2DHozhGvQnUMKwvKLfXaEry2RzVNeBOkP2nJPh6i8dxtgZ4yOo8YutVqpl9J+FpNbUeP9DEv3rajCsFNVYAJ2SoouV2/ndcAVE/fincP3LhOmMaPSPK4JHV49ygKj1iMYsBbc9liNNRAB5hg+syFu8IQbQK9Oq8xwveY0kAzd61E5yrQiuTWFYevYWPrnycjkTEcDkFA359nKnd3jujvsqh8++3q2i/91RO/xFwRCd3P4ximJRMLeubgimZtp7Axcz4SxGpZXrm/YwHQz+IkbAhtCo4kxfUt7gnK2vu0tfCS3Sht+PYfT+n6BaETsI4gx3KulsTM/JMkDV08VullYQq8SO5XoIK+xxbtFG5KEGHHlwNH/AsdJ2dP4dKOo8I3xnuzYcadtQtYMabqGDk02eo8rqopApFlbav0OhWPwzMbk70IxAZbOcwx90SBUgqLGpnoGw7+ob9Zh4l+hqQplXQ8lcxhGjD3lsVmdaMtcFuAuBHY3DNkytWnMm1sBERxgKNhcy4+E/IQLNXRjqhvoHhXYVZeBXmMf50lSQ==";

  allKeys = [ nas admin ];
in
{
  "samba-password.age".publicKeys = allKeys;
}
